# -*- coding: utf-8 -*-
"""capetown-invest.com demand core, Semrush 2026-09-07.
Format: (keyword, database, volume, cpc, semrush_intent, cluster, geo_level)
intent codes: 0 commercial, 1 informational, 2 navigational, 3 transactional
"""
D = [
# ================= ZA — metro commercial head =================
("houses for sale in cape town","za",18100,0.05,3,"commercial","metro"),
("apartments for sale cape town","za",4400,0.13,3,"commercial","metro"),
("property for sale cape town","za",4400,0.08,3,"commercial","metro"),
("cape town property for sale","za",4400,0.08,3,"commercial","metro"),
("cape town apartments","za",2900,0.18,0,"commercial","metro"),
("cape town houses","za",2400,0.09,1,"commercial","metro"),
("house for sale cape town","za",1900,0.05,3,"commercial","metro"),
("cape town property","za",1600,0.20,0,"commercial","metro"),
("property cape town","za",1600,0.20,0,"commercial","metro"),
("houses for sale cape town","za",1600,0.04,3,"commercial","metro"),
("new developments cape town","za",1600,0.25,0,"newbuild","metro"),
("new developments in cape town","za",1600,0.25,0,"newbuild","metro"),
("cape town real estate","za",390,0.11,0,"commercial","metro"),
("flats for sale cape town","za",210,0.13,3,"commercial","metro"),
("cape town property prices","za",140,0.09,3,"price","metro"),
("property prices cape town","za",140,0.09,3,"price","metro"),
("cape town house prices","za",140,0.10,0,"price","metro"),
("cape town property market","za",20,0.29,None,"market","metro"),
("property developments cape town","za",260,0.40,0,"newbuild","metro"),
("new build cape town","za",10,0,None,"newbuild","metro"),
("new developments western cape","za",170,0.15,1,"newbuild","region"),
# ================= ZA — country level =================
("houses for sale in south africa","za",880,0.06,3,"commercial","country"),
("property for sale south africa","za",590,0.09,3,"commercial","country"),
("south africa property","za",320,0.11,0,"commercial","country"),
("property in south africa","za",320,0.11,0,"commercial","country"),
("south africa real estate","za",260,0.18,0,"commercial","country"),
("buy property in south africa","za",140,0.32,1,"commercial","country"),
("south africa property market","za",110,0.38,1,"market","country"),
("south africa house prices","za",30,0,None,"price","country"),
# ================= ZA — region level =================
("houses for sale western cape","za",1900,0.03,3,"commercial","region"),
("western cape property for sale","za",1600,0.03,3,"commercial","region"),
("western cape property","za",320,0.03,0,"commercial","region"),
("garden route property for sale","za",480,0.02,3,"commercial","region"),
("garden route property","za",170,0.02,0,"commercial","region"),
("atlantic seaboard property for sale","za",210,0.03,3,"commercial","macro"),
("atlantic seaboard","za",590,0.64,0,"choice","macro"),
("southern suburbs cape town","za",5400,0.29,1,"choice","macro"),
("northern suburbs cape town","za",2900,0.29,1,"choice","macro"),
("city bowl cape town","za",480,0.37,1,"choice","macro"),
("southern suburbs property","za",110,0.05,0,"commercial","macro"),
("atlantic seaboard property","za",10,0.05,None,"commercial","macro"),
("cape flats property","za",10,0,None,"commercial","macro"),
("property for sale in southern suburbs cape town","za",1000,0.04,3,"commercial","macro"),
("property for sale in northern suburbs cape town","za",210,0.02,3,"commercial","macro"),
# ================= ZA — suburb "for sale" (transactional) =================
("houses for sale in durbanville","za",6600,0.02,3,"commercial","suburb"),
("houses for sale in paarl","za",5400,0.37,3,"commercial","suburb"),
("houses for sale in somerset west","za",4400,0.03,3,"commercial","suburb"),
("property for sale in hermanus","za",3600,0.02,3,"commercial","suburb"),
("houses for sale in stellenbosch","za",2900,0.02,3,"commercial","suburb"),
("houses for sale in hermanus","za",2900,0.02,3,"commercial","suburb"),
("houses for sale in plumstead","za",2900,0.02,3,"commercial","suburb"),
("property for sale in durbanville","za",2900,0.02,3,"commercial","suburb"),
("property for sale in paarl","za",2900,0.37,3,"commercial","suburb"),
("property for sale in somerset west","za",2900,0.06,3,"commercial","suburb"),
("property for sale in stellenbosch","za",2400,0.05,3,"commercial","suburb"),
("property for sale in langebaan","za",2400,0.03,3,"commercial","suburb"),
("houses for sale in langebaan","za",2400,0.02,3,"commercial","suburb"),
("houses for sale in rondebosch","za",1900,0.02,3,"commercial","suburb"),
("houses for sale in fish hoek","za",1900,0.01,3,"commercial","suburb"),
("property for sale in kleinmond","za",1900,0.01,3,"commercial","suburb"),
("property for sale in strand","za",1900,0.02,3,"commercial","suburb"),
("houses for sale in newlands","za",1600,0.02,3,"commercial","suburb"),
("houses for sale in muizenberg","za",1600,0.02,3,"commercial","suburb"),
("property for sale in yzerfontein","za",1600,0.01,3,"commercial","suburb"),
("houses for sale in claremont","za",1300,0.02,3,"commercial","suburb"),
("houses for sale in hout bay","za",1300,0.02,3,"commercial","suburb"),
("property for sale in hout bay","za",1300,0.02,3,"commercial","suburb"),
("property for sale in fish hoek","za",1300,0.01,3,"commercial","suburb"),
("property for sale in melkbosstrand","za",1300,0.02,3,"commercial","suburb"),
("property for sale in gordons bay","za",1300,0.02,3,"commercial","suburb"),
("houses for sale in clifton","za",1000,0.01,3,"commercial","suburb"),
("property for sale in franschhoek","za",1000,0.01,3,"commercial","suburb"),
("property for sale in rondebosch","za",1000,0.03,3,"commercial","suburb"),
("houses for sale in melkbosstrand","za",1000,0.01,3,"commercial","suburb"),
("houses for sale in wynberg","za",1000,0.02,3,"commercial","suburb"),
("houses for sale in tokai","za",1000,0.02,3,"commercial","suburb"),
("apartments for sale in sea point","za",1000,0.12,3,"commercial","suburb"),
("property for sale in muizenberg","za",880,0.02,3,"commercial","suburb"),
("property for sale in noordhoek","za",880,0.01,3,"commercial","suburb"),
("houses for sale in noordhoek","za",880,0.01,3,"commercial","suburb"),
("property for sale in plumstead","za",880,0.02,3,"commercial","suburb"),
("property for sale in tokai","za",880,0.02,3,"commercial","suburb"),
("property for sale in wellington","za",880,0.01,3,"commercial","suburb"),
("plot for sale cape town","za",880,0.11,3,"asset-land","metro"),
("houses for sale in constantia","za",720,0.01,3,"commercial","suburb"),
("houses for sale in franschhoek","za",720,0.01,3,"commercial","suburb"),
("property for sale in milnerton","za",720,0.03,3,"commercial","suburb"),
("land for sale cape town","za",720,0.10,3,"asset-land","metro"),
("houses for sale in woodstock","za",590,0.02,3,"commercial","suburb"),
("houses for sale in sea point","za",590,0.03,3,"commercial","suburb"),
("houses for sale in fresnaye","za",590,0.02,3,"commercial","suburb"),
("property for sale in kalk bay","za",590,0.02,3,"commercial","suburb"),
("property for sale in kommetjie","za",590,0.02,3,"commercial","suburb"),
("commercial property for sale cape town","za",590,0.24,3,"asset-commercial","metro"),
("houses for sale in bantry bay","za",480,0.01,3,"commercial","suburb"),
("houses for sale in blouberg","za",480,0.02,3,"commercial","suburb"),
("houses for sale in camps bay","za",480,0.02,3,"commercial","suburb"),
("houses for sale in milnerton","za",480,0.02,3,"commercial","suburb"),
("houses for sale in century city","za",480,0.04,3,"commercial","suburb"),
("property for sale in table view","za",480,0.02,3,"commercial","suburb"),
("property for sale in tamboerskloof","za",480,0.03,3,"commercial","suburb"),
("property for sale in bergvliet","za",480,0.03,3,"commercial","suburb"),
("property for sale in century city","za",480,0.10,3,"commercial","suburb"),
("property for sale in claremont","za",390,0.03,3,"commercial","suburb"),
("property for sale in clifton","za",390,0.02,3,"commercial","suburb"),
("houses for sale in llandudno","za",390,0.02,3,"commercial","suburb"),
("property for sale in vredehoek","za",390,0.03,3,"commercial","suburb"),
("property for sale in big bay","za",390,0.02,3,"commercial","suburb"),
("property for sale in newlands cape town","za",390,0.08,3,"commercial","suburb"),
("apartments for sale in camps bay","za",390,0.12,3,"commercial","suburb"),
("property for sale in bantry bay","za",320,0.02,3,"commercial","suburb"),
("property for sale in woodstock","za",320,0.03,3,"commercial","suburb"),
("houses for sale in kalk bay","za",320,0.01,3,"commercial","suburb"),
("houses for sale in bloubergstrand","za",260,0.02,3,"commercial","suburb"),
("houses for sale in tamboerskloof","za",260,0.02,3,"commercial","suburb"),
("property for sale in bishopscourt","za",260,0.02,3,"commercial","suburb"),
("property for sale in scarborough","za",260,0.01,3,"commercial","suburb"),
("houses for sale in table view","za",210,0.02,3,"commercial","suburb"),
("property for sale in sea point","za",210,0.04,3,"commercial","suburb"),
("property for sale in bloubergstrand","za",210,0.02,3,"commercial","suburb"),
("property for sale in camps bay","za",170,0.02,3,"commercial","suburb"),
("property for sale in constantia","za",170,0.02,3,"commercial","suburb"),
("property for sale in llandudno","za",170,0.03,3,"commercial","suburb"),
("property for sale in st james","za",170,0.05,3,"commercial","suburb"),
("houses for sale in simons town","za",140,0.01,3,"commercial","suburb"),
("houses for sale in gardens","za",140,0.05,3,"commercial","suburb"),
("houses for sale in green point","za",40,0.02,None,"commercial","suburb"),
("property for sale in simons town","za",20,0.01,None,"commercial","suburb"),
("property for sale in observatory","za",20,0.04,None,"commercial","suburb"),
("apartments for sale in cape town city centre","za",20,0.11,None,"commercial","suburb"),
# ================= ZA — bare suburb names (mixed intent, tourism risk) =================
("v&a waterfront","za",201000,0.54,2,"navigational-place","suburb"),
("stellenbosch","za",110000,0.18,1,"place","suburb"),
("hout bay","za",60500,0.58,1,"place","suburb"),
("somerset west","za",60500,0.54,1,"place","suburb"),
("paarl","za",60500,0.46,1,"place","suburb"),
("camps bay","za",49500,0.35,1,"place","suburb"),
("franschhoek","za",49500,0.65,1,"place","suburb"),
("hermanus","za",49500,0.36,1,"place","suburb"),
("sea point","za",40500,0.39,1,"place","suburb"),
("century city","za",40500,0.77,1,"place","suburb"),
("durbanville","za",33100,0.38,1,"place","suburb"),
("muizenberg","za",33100,0.45,1,"place","suburb"),
("kalk bay","za",33100,0.47,1,"place","suburb"),
("simons town","za",33100,0.61,1,"place","suburb"),
("bloubergstrand","za",27100,0.47,1,"place","suburb"),
("fish hoek","za",27100,0.36,1,"place","suburb"),
("melkbosstrand","za",27100,0.51,1,"place","suburb"),
("waterfront cape town","za",22200,0.23,2,"place","suburb"),
("milnerton","za",22200,0.46,1,"place","suburb"),
("wynberg cape town","za",22200,0.24,1,"place","suburb"),
("constantia","za",18100,0.73,1,"place","suburb"),
("claremont","za",18100,0.45,1,"place","suburb"),
("rondebosch","za",18100,0.65,1,"place","suburb"),
("table view","za",18100,0.54,1,"place","suburb"),
("noordhoek","za",18100,0.61,1,"place","suburb"),
("kommetjie","za",14800,0.41,1,"place","suburb"),
("plumstead","za",12100,0.01,1,"place","suburb"),
("tokai","za",8100,0.39,1,"place","suburb"),
("vredehoek","za",6600,0.34,1,"place","suburb"),
("big bay","za",6600,0.55,1,"place","suburb"),
("llandudno","za",5400,0.48,1,"place","suburb"),
("bantry bay","za",5400,0.29,1,"place","suburb"),
("tamboerskloof","za",5400,0.67,1,"place","suburb"),
("de waterkant","za",5400,0.65,1,"place","suburb"),
("blouberg","za",5400,0.28,1,"place","suburb"),
("bergvliet","za",5400,0.00,1,"place","suburb"),
("oranjezicht","za",5400,0.62,2,"place","suburb"),
("woodstock cape town","za",4400,0.44,1,"place","suburb"),
("observatory cape town","za",4400,0.81,1,"place","suburb"),
("fresnaye","za",3600,0.26,1,"place","suburb"),
("gardens cape town","za",2900,0.38,1,"place","suburb"),
("green point cape town","za",2400,0.56,1,"place","suburb"),
("newlands cape town","za",1900,0.50,1,"place","suburb"),
("clifton cape town","za",1900,0.23,1,"place","suburb"),
("salt river cape town","za",1600,0.65,1,"place","suburb"),
("bishopscourt","za",1600,0.13,1,"place","suburb"),
# ================= ZA — legal / process / money =================
("transfer duty calculator","za",2400,0.02,0,"legal","country"),
("transfer duty south africa","za",880,0.03,1,"legal","country"),
("city of cape town rates","za",390,0.00,2,"legal","metro"),
("can foreigners buy property in south africa","za",140,0.00,1,"legal-foreign","country"),
("buying property in south africa","za",140,0.32,1,"legal","country"),
("rates and taxes cape town","za",140,0.00,1,"legal","metro"),
("conveyancing fees calculator","za",90,0.43,0,"legal","country"),
("conveyancing fees south africa","za",70,0.42,None,"legal","country"),
("municipal rates cape town","za",40,0.00,None,"legal","metro"),
("electrical compliance certificate cape town","za",40,1.06,None,"legal","metro"),
("beetle certificate cape town","za",30,1.10,None,"legal","metro"),
("how to buy property in south africa","za",20,0.40,None,"legal","country"),
("buying property in south africa as a foreigner","za",20,0.01,None,"legal-foreign","country"),
("foreigners buying property in south africa","za",20,0.01,None,"legal-foreign","country"),
("non resident mortgage south africa","za",20,0.00,None,"money","country"),
("special power of attorney south africa","za",20,0.25,None,"legal","country"),
("exchange control south africa","za",20,0.00,None,"money","country"),
("repatriation of funds south africa","za",20,0.00,None,"money","country"),
("sectional title vs freehold","za",20,0.00,None,"legal","country"),
("sectional title levies","za",20,0.00,None,"legal","country"),
("property transfer process south africa","za",20,0.08,None,"legal","country"),
("occupational rent south africa","za",20,0.00,None,"legal","country"),
("offer to purchase south africa","za",20,0.22,None,"legal","country"),
("plumbing certificate cape town","za",20,0.00,None,"legal","metro"),
("section 35a withholding tax","za",10,0.00,None,"legal-foreign","country"),
("property rates cape town","za",10,0.00,None,"legal","metro"),
("nhbrc warranty","za",10,0.00,None,"legal","country"),
("snagging inspection","za",10,0.00,None,"legal","country"),
# ================= ZA — visa / relocation =================
("south africa critical skills visa","za",480,0.26,1,"visa","country"),
("emigrating to south africa","za",480,0.32,1,"relocation","country"),
("south africa permanent residence","za",390,0.25,1,"visa","country"),
("south africa retirement visa","za",70,0.09,None,"visa","country"),
("retired person visa south africa","za",70,0.06,None,"visa","country"),
("moving to cape town","za",30,1.47,None,"relocation","metro"),
("semigration to cape town","za",20,0.00,None,"relocation","metro"),
("relocating to cape town","za",10,0.73,None,"relocation","metro"),
# ================= ZA — yield / STR / management =================
("airbnb cape town","za",14800,0.25,2,"str","metro"),
("property management cape town","za",320,1.00,0,"management","metro"),
("airbnb rules cape town","za",20,0.00,None,"str","metro"),
("buy to let cape town","za",20,0.38,None,"yield","metro"),
("rental yield south africa","za",20,0.00,None,"yield","country"),
("property management fees south africa","za",20,0.55,None,"management","country"),
("cape town property market forecast","za",10,0.00,None,"market","metro"),
# ================= ZA — investment frame (our current architecture) =================
("south africa property investment","za",720,0.60,1,"investment","country"),
("property investment south africa","za",720,0.60,1,"investment","country"),
("property investment cape town","za",140,0.69,0,"investment","metro"),
("investment property cape town","za",140,0.69,0,"investment","metro"),
("south africa real estate investment","za",50,0.67,None,"investment","country"),
("best place to invest in property south africa","za",20,0.44,None,"investment","country"),
# ZERO-VOLUME in za, tested explicitly:
("{26 suburbs} property investment","za",0,0,None,"investment-ZERO","suburb"),
("cape town property investment","za",0,0,None,"investment-ZERO","metro"),
("western cape property investment","za",0,0,None,"investment-ZERO","region"),
("century city property investment","za",0,0,None,"investment-ZERO","suburb"),
("stellenbosch property investment","za",0,0,None,"investment-ZERO","suburb"),
("atlantic seaboard property investment","za",0,0,None,"investment-ZERO","macro"),
("southern suburbs property investment","za",0,0,None,"investment-ZERO","macro"),
("invest in cape town property","za",0,0,None,"investment-ZERO","metro"),
("cape town real estate investment","za",0,0,None,"investment-ZERO","metro"),
("best areas to invest in cape town","za",0,0,None,"investment-ZERO","metro"),
("cape town property investment guide","za",0,0,None,"investment-ZERO","metro"),
("is cape town property a good investment","za",0,0,None,"investment-ZERO","metro"),
("cape town property investment 2026","za",0,0,None,"investment-ZERO","metro"),
("off plan property cape town","za",0,0,None,"newbuild-ZERO","metro"),
("cape town short term rental bylaw","za",0,0,None,"str-ZERO","metro"),
("cape town property price growth","za",0,0,None,"market-ZERO","metro"),
("western cape property prices","za",0,0,None,"price-ZERO","region"),
# ================= ZA — life =================
("international schools cape town","za",1000,0.19,2,"life","metro"),
("load shedding cape town","za",1000,0.00,1,"life","metro"),
("private schools cape town","za",480,0.66,0,"life","metro"),
("is cape town safe","za",480,0.00,1,"life","metro"),
("crime in cape town","za",390,0.00,1,"life","metro"),
("cost of living cape town","za",210,0.00,1,"life","metro"),
("best suburbs to live in cape town","za",30,0.00,None,"choice","metro"),
("where to live in cape town","za",20,0.12,None,"choice","metro"),
# ================= ZA — adjacent assets / projects / developers =================
("signatura","za",14800,0.43,1,"developer","brand"),
("val de vie","za",6600,0.43,2,"project","brand"),
("balwin properties","za",5400,0.43,2,"developer","brand"),
("farm for sale western cape","za",4400,0.02,3,"asset-farm","region"),
("pearl valley","za",2900,0.69,1,"project","brand"),
("foreshore place","za",2900,0.44,1,"project","brand"),
("silo district","za",2400,0.00,1,"project","brand"),
("growthpoint properties","za",2400,0.29,2,"developer","brand"),
("rabie property group","za",590,0.37,2,"developer","brand"),
("retirement village cape town","za",320,0.15,0,"asset-retirement","metro"),
("devmco group","za",320,0.00,2,"developer","brand"),
("amdec group","za",320,0.00,2,"developer","brand"),
("two oceans beach","za",320,0.00,1,"project","brand"),
("berman brothers","za",210,0.00,1,"developer","brand"),
("wine farm for sale western cape","za",170,0.03,3,"asset-farm","region"),
("harbour arch cape town","za",140,0.20,2,"project","brand"),
("the yacht club cape town","za",140,0.00,0,"project","brand"),
("blok cape town","za",90,0.57,2,"developer","brand"),
("the ridge clifton","za",30,0.00,None,"project","brand"),
("rockwell cape town","za",20,0.38,None,"project","brand"),
("granger bay waterfront","za",20,0.00,None,"project","brand"),
("zero2one cape town","za",10,0.00,None,"project","brand"),
# ================= UK =================
("property24","uk",3600,0.03,2,"navigational-portal","country"),
("is cape town safe","uk",2400,0.46,1,"life","metro"),
("houses for sale in cape town","uk",720,0.10,3,"commercial","metro"),
("houses for sale in south africa","uk",720,0.10,3,"commercial","country"),
("private property south africa","uk",480,0.03,2,"navigational-portal","country"),
("cape town property for sale","uk",390,0.10,3,"commercial","metro"),
("property for sale in south africa","uk",390,0.06,3,"commercial","country"),
("moving to south africa","uk",320,1.01,1,"relocation","country"),
("property for sale in cape town","uk",260,0.10,3,"commercial","metro"),
("south africa visa requirements","uk",260,1.05,1,"visa","country"),
("moving to south africa from uk","uk",260,1.75,1,"relocation","country"),
("cape town property","uk",210,0.26,0,"commercial","metro"),
("apartments for sale cape town","uk",170,0.17,3,"commercial","metro"),
("south africa property for sale","uk",170,0.06,3,"commercial","country"),
("south africa property","uk",140,0.14,0,"commercial","country"),
("cost of living south africa","uk",140,0.00,1,"life","country"),
("pam golding properties","uk",140,0.00,2,"navigational-agency","brand"),
("hermanus property for sale","uk",110,0.03,3,"commercial","suburb"),
("south africa real estate","uk",90,0.27,None,"commercial","country"),
("franschhoek property for sale","uk",90,0.23,None,"commercial","suburb"),
("seeff properties","uk",90,0.00,None,"navigational-agency","brand"),
("relocating to south africa","uk",70,1.07,None,"relocation","country"),
("south africa retirement visa","uk",70,0.81,None,"visa","country"),
("south africa digital nomad visa","uk",70,7.34,None,"visa","country"),
("international schools cape town","uk",70,0.10,None,"life","metro"),
("cost of living cape town","uk",50,0.00,None,"life","metro"),
("camps bay property for sale","uk",50,0.22,None,"commercial","suburb"),
("cape town real estate","uk",40,0.06,None,"commercial","metro"),
("cape town apartments for sale","uk",40,0.24,None,"commercial","metro"),
("constantia property for sale","uk",40,0.06,None,"commercial","suburb"),
("moving to cape town","uk",40,1.06,None,"relocation","metro"),
("clifton property for sale","uk",40,1.15,None,"commercial","suburb"),
("living in cape town","uk",30,0.51,None,"life","metro"),
("cape town villas for sale","uk",30,0.35,None,"commercial","metro"),
("hout bay property for sale","uk",30,0.02,None,"commercial","suburb"),
("south africa permanent residence","uk",30,0.67,None,"visa","country"),
("cape town property investment","uk",20,0.00,None,"investment","metro"),
("property investment south africa","uk",20,2.29,None,"investment","country"),
("south africa property investment","uk",10,2.29,None,"investment","country"),
("invest in south africa property","uk",0,2.42,None,"investment-ZERO","country"),
("is cape town property a good investment","uk",0,0,None,"investment-ZERO","metro"),
("cape town luxury property","uk",0,0,None,"commercial-ZERO","metro"),
("atlantic seaboard property for sale","uk",0,0,None,"commercial-ZERO","macro"),
("winelands property for sale","uk",0,0,None,"commercial-ZERO","region"),
("rental yield south africa","uk",0,0,None,"yield-ZERO","country"),
("stellenbosch property for sale","uk",20,0.26,None,"commercial","suburb"),
("somerset west property for sale","uk",20,0.11,None,"commercial","suburb"),
("cape winelands property for sale","uk",20,0.00,None,"commercial","region"),
("v&a waterfront apartments for sale","uk",20,0.00,None,"commercial","suburb"),
("garden route property for sale","uk",10,0.00,None,"commercial","region"),
("sea point property for sale","uk",10,0.12,None,"commercial","suburb"),
("transfer duty south africa","uk",20,0.00,None,"legal","country"),
("non resident mortgage south africa","uk",20,0.00,None,"money","country"),
("exchange control south africa","uk",20,0.00,None,"money","country"),
("conveyancing south africa","uk",20,0.00,None,"legal","country"),
("can foreigners buy property in south africa","uk",20,0.00,None,"legal-foreign","country"),
("buying property in cape town as a foreigner","uk",20,0.00,None,"legal-foreign","metro"),
("foreigners buying property in south africa","uk",20,0.01,None,"legal-foreign","country"),
("buying property in south africa as a foreigner","uk",10,0.00,None,"legal-foreign","country"),
("property management cape town","uk",20,0.00,None,"management","metro"),
("retire in south africa","uk",20,0.94,None,"relocation","country"),
("retirement in south africa","uk",20,0.94,None,"relocation","country"),
("best places to live in cape town","uk",20,0.75,None,"choice","metro"),
("cape town property market","uk",20,0.00,None,"market","metro"),
("new developments cape town","uk",10,0.52,None,"newbuild","metro"),
("emigrating to south africa","uk",10,1.15,None,"relocation","country"),
# ================= US =================
("property24","us",4400,0.02,2,"navigational-portal","country"),
("is cape town safe","us",2900,0.22,1,"life","metro"),
("houses for sale in south africa","us",880,0.03,3,"commercial","country"),
("cape town real estate","us",480,0.02,0,"commercial","metro"),
("south africa real estate","us",480,0.03,0,"commercial","country"),
("houses for sale in cape town","us",480,0.02,3,"commercial","metro"),
("moving to south africa","us",210,1.24,1,"relocation","country"),
("south africa visa requirements","us",210,0.00,1,"visa","country"),
("pam golding properties","us",170,0.00,2,"navigational-agency","brand"),
("private property south africa","us",170,0.04,2,"navigational-portal","country"),
("south africa retirement visa","us",170,0.64,1,"visa","country"),
("apartments for sale cape town","us",140,0.09,3,"commercial","metro"),
("property for sale in south africa","us",140,0.03,3,"commercial","country"),
("cost of living cape town","us",140,0.00,1,"life","metro"),
("cost of living south africa","us",140,0.00,1,"life","country"),
("south africa digital nomad visa","us",140,0.00,1,"visa","country"),
("cape town property for sale","us",110,0.05,3,"commercial","metro"),
("relocating to south africa","us",90,0.72,1,"relocation","country"),
("living in cape town","us",90,0.00,1,"life","metro"),
("cape town property","us",70,0.47,0,"commercial","metro"),
("south africa permanent residence","us",70,0.00,1,"visa","country"),
("international schools cape town","us",70,0.00,0,"life","metro"),
("can foreigners buy property in south africa","us",50,0.00,1,"legal-foreign","country"),
("retire in south africa","us",50,0.71,1,"relocation","country"),
("property investment south africa","us",40,1.13,1,"investment","country"),
("south africa property for sale","us",40,0.03,3,"commercial","country"),
("cape town apartments for sale","us",40,0.09,3,"commercial","metro"),
("retirement in south africa","us",40,1.05,1,"relocation","country"),
("moving to cape town","us",40,1.71,1,"relocation","metro"),
("south africa property","us",30,0.32,None,"commercial","country"),
("moving to south africa from uk","us",30,0.00,None,"relocation","country"),
("cape town villas for sale","us",20,0.05,None,"commercial","metro"),
("property for sale in cape town","us",20,0.02,None,"commercial","metro"),
("buy property in cape town","us",20,0.02,None,"commercial","metro"),
("cape town property investment","us",20,0.00,None,"investment","metro"),
("seeff properties","us",20,0.00,None,"navigational-agency","brand"),
("franschhoek property for sale","us",20,0.00,None,"commercial","suburb"),
("v&a waterfront apartments for sale","us",20,0.00,None,"commercial","suburb"),
("cape winelands property for sale","us",20,0.00,None,"commercial","region"),
("camps bay property for sale","us",10,0.02,None,"commercial","suburb"),
("hermanus property for sale","us",10,0.01,None,"commercial","suburb"),
("somerset west property for sale","us",10,0.02,None,"commercial","suburb"),
("clifton property for sale","us",10,0.28,None,"commercial","suburb"),
("cape town luxury property","us",0,0,None,"commercial-ZERO","metro"),
("stellenbosch property for sale","us",0,0.03,None,"commercial-ZERO","suburb"),
("sea point property for sale","us",0,0.23,None,"commercial-ZERO","suburb"),
("constantia property for sale","us",0,0,None,"commercial-ZERO","suburb"),
("garden route property for sale","us",0,0,None,"commercial-ZERO","region"),
("hout bay property for sale","us",0,0.03,None,"commercial-ZERO","suburb"),
("buy to let cape town","us",0,0,None,"yield-ZERO","metro"),
("rental yield south africa","us",0,0,None,"yield-ZERO","country"),
# ================= DE (German language) =================
("property24","de",1300,0.02,2,"navigational-portal","country"),
("haus kaufen kapstadt","de",480,0.27,3,"commercial","metro"),
("immobilien kapstadt","de",390,0.14,0,"commercial","metro"),
("ist kapstadt sicher","de",390,0.42,1,"life","metro"),
("immobilien südafrika","de",320,0.23,0,"commercial","country"),
("haus kaufen südafrika","de",320,0.09,3,"commercial","country"),
("auswandern südafrika","de",260,0.24,1,"relocation","country"),
("kapstadt wohnung kaufen","de",170,0.01,3,"commercial","metro"),
("wohnung kaufen kapstadt","de",140,0.22,3,"commercial","metro"),
("immobilien kapstadt kaufen","de",140,0.05,3,"commercial","metro"),
("haus in südafrika kaufen","de",140,0.12,3,"commercial","country"),
("cape town property","de",110,0.25,1,"commercial","metro"),
("cape town real estate","de",110,0.22,1,"commercial","metro"),
("südafrika immobilien kaufen","de",90,0.11,3,"commercial","country"),
("south africa real estate","de",90,0.04,1,"commercial","country"),
("is cape town safe","de",90,0.00,1,"life","metro"),
("kapstadt haus mieten","de",70,0.64,0,"rental","metro"),
("houses for sale in cape town","de",70,0.12,1,"commercial","metro"),
("apartments for sale cape town","de",70,0.15,1,"commercial","metro"),
("leben in kapstadt","de",40,0.25,None,"life","metro"),
("immobilienpreise kapstadt","de",40,0.00,None,"price","metro"),
("auswandern nach kapstadt","de",30,0.26,None,"relocation","metro"),
("pam golding properties","de",30,0.00,None,"navigational-agency","brand"),
("rentner visum südafrika","de",20,0.66,None,"visa","country"),
("südafrika auswandern voraussetzungen","de",20,0.24,None,"relocation","country"),
("weingut südafrika kaufen","de",20,0.00,None,"asset-farm","country"),
("ferienhaus südafrika kaufen","de",20,0.00,None,"commercial","country"),
("stellenbosch immobilien","de",10,0.00,None,"commercial","suburb"),
("hermanus immobilien","de",0,0,None,"commercial-ZERO","suburb"),
# ================= NL =================
("property24","nl",1300,0.02,2,"navigational-portal","country"),
("is kaapstad veilig","nl",210,0.25,1,"life","metro"),
("is cape town safe","nl",110,0.00,1,"life","metro"),
("houses for sale in cape town","nl",90,0.05,1,"commercial","metro"),
("huis kopen kaapstad","nl",70,0.23,2,"commercial","metro"),
("huis kopen zuid-afrika","nl",50,0.29,3,"commercial","country"),
("apartments for sale cape town","nl",40,0.25,1,"commercial","metro"),
("moving to south africa","nl",30,2.79,None,"relocation","country"),
("pam golding properties","nl",30,0.00,None,"navigational-agency","brand"),
("emigreren naar zuid-afrika","nl",0,2.32,1,"relocation-ZERO","country"),
# ================= AU =================
("property24","au",1300,0.02,2,"navigational-portal","country"),
("is cape town safe","au",590,0.11,1,"life","metro"),
("moving to south africa","au",390,4.17,1,"relocation","country"),
("houses for sale in south africa","au",210,0.05,3,"commercial","country"),
("south africa real estate","au",170,0.04,0,"commercial","country"),
("houses for sale in cape town","au",140,0.04,3,"commercial","metro"),
("cape town real estate","au",110,0.03,0,"commercial","metro"),
("property for sale in south africa","au",70,0.22,3,"commercial","country"),
("cape town property","au",40,0.04,None,"commercial","metro"),
("cape town property for sale","au",40,0.03,None,"commercial","metro"),
# ================= AE =================
("property24","ae",590,0.01,2,"navigational-portal","country"),
("is cape town safe","ae",170,0.06,1,"life","metro"),
("houses for sale in cape town","ae",110,0.03,1,"commercial","metro"),
("property for sale in cape town","ae",90,0.26,1,"commercial","metro"),
("cape town property for sale","ae",90,0.26,1,"commercial","metro"),
("property for sale in south africa","ae",30,0.10,0,"commercial","country"),
("stellenbosch property for sale","ae",30,0.05,1,"commercial","suburb"),
("living in cape town","ae",30,0.00,None,"life","metro"),
# ================= CA =================
("property24","ca",590,0.03,2,"navigational-portal","country"),
("is cape town safe","ca",480,0.10,1,"life","metro"),
("houses for sale in cape town","ca",140,0.03,3,"commercial","metro"),
("cape town real estate","ca",110,0.02,0,"commercial","metro"),
("houses for sale in south africa","ca",110,0.04,3,"commercial","country"),
("south africa real estate","ca",90,0.10,0,"commercial","country"),
("moving to south africa","ca",30,0.61,None,"relocation","country"),
("retire in south africa","ca",20,0.83,None,"relocation","country"),
]
